services:
  - type: web
    name: twitch-chatgpt-bot
    runtime: node
    branch: main
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        value: "false"
      - key: CHANNELS
        value: "AnnieVnKr"
      - key: GPT_MODE
        value: "CHAT"
      - key: HISTORY_LENGTH
        value: "3"
      - key: MODEL_NAME
        value: "gpt-3.5-turbo"
      - key: COMMAND_NAME
        value: "chat"
      - key: TWITCH_USER  # https://dev.twitch.tv/console
        value: "false"
      - key: TWITCH_AUTH  # https://twitchapps.com/tmi/
        value: "oauth:tgwxstauca9cg9i2ouy3s7i0zuup5q"
      - key: SEND_USERNAME
        value: "true"
      - key: ENABLE_TTS
        value: "false"
      - key: ENABLE_CHANNEL_POINTS
        value: "false"
